phrase:
  access_token: 8e7d758f2ffe70fb7803917b81e90000d236ace20b698ca126ca0017ff1103bf
  project_id: 47b1f46fd10f7f99a4ab6f1b5c726b7d
  
  push:
    sources:
      - file: ./go_i18n.json
        params:
          file_format: go_i18n
          locale_id: en
          update_translations: true
          autotranslate: true

  pull:
    targets:
      - file: ./go_i18n.json
        params:
          file_format: go_i18n
